name: dnanalyzer
channels:
  - conda-forge
  - defaults
dependencies:
  - ffmpeg
  - jq
  - sox
  - imagemagick
  - gmp
  - jemalloc
  - nodejs
  - openssl
  - readline
  - ruby=2.6.6
  - yaml
  - yamllint
  - zlib
  - libxml2
  - pkg-config
  - pandas
  - pyyaml
  - gxx_linux-64

