name: Deploy

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - fix-flask

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host apps.galaxyproject.eu
            	User dokku
            	Port 8080

      - name: Deploy 🚀
        run: |
            git remote add dokku dokku@apps.galaxyproject.eu:dnanalyzer
            git push dokku main
